apiVersion: v1
kind: Service
metadata:
  name: eureka-server-uat-lb
  labels:
    app: eureka-server-uat
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      nodePort: 30030
  selector:
    app: eureka-server-uat
