server:
  port: 8080

spring:
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
    health:
      show-details: always
  endpoint:
    chaosmonkey:
      enabled: true
  metrics:
    tags:
      application: RestaurantApplication
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 100ms, 150ms, 250ms, 500ms, 1s
      enable:
        jvm: true

chaos:
  monkey:
    watcher:
      controller: true
      restController: true
      service: true
      repository: true
      component: true